### ISSUE TITLE
Lesson 3 with child theme - custom palette needs `!important`

### ISSUE THREAD

**Issue by colorful-tones** [aurooba/twentytwentyone-child#2]
Lesson 3 branch custom CSS colors do not work as they exist. Due to TwentyTwentyOne's CSS targeting of `background-color` and `color` the front end CSS does not work. One must add `!important` to the `@each` loop to truly override the colors.

Before: 

```
@each $colour in $palette {
  .has-#{nth($colour, 1)}-background-color {
    background: nth($colour, 2);
  }
  .has-#{nth($colour, 1)}-color {
    color:nth($colour, 2);
  }
}
```

Recommeded: 

```
@each $colour in $palette {
  .has-#{nth($colour, 1)}-background-color {
    background: nth($colour, 2) !important;
  }
  .has-#{nth($colour, 1)}-color {
    color:nth($colour, 2) !important;
  }
}
```

**Comment by aurooba** [comment]
Hmm, I didn't encounter this when I tested it against Twenty Twenty One. Will check again. I'd prefer not to add `!important` to this. Thanks for the heads up, @colorful-tones!

**Comment by colorful-tones** [comment]
Yeah, I avoid `!important` at all costs. That was mostly my quick fix to keep things moving. I'm sure a better solve can be made. 👍

**Comment by aurooba** [comment]
@colorful-tones Just testing this today, and I'm not able to recreate the issue. The colours look to be working for me on both front-end and in the block editor without the `!important`. Can you share how you tested this?

**Comment by colorful-tones** [comment]
@aurooba really swamped and can not re-test. Sorry! 🤦 

Feel free to chalk it up to user error and close this out if nobody else is reporting.

**Comment by aurooba** [comment]
All good. Thanks @colorful-tones  :)
